# Generated by Django 5.0.3 on 2024-06-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_profile_picture',
            field=models.BooleanField(default=False, verbose_name='Has Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Admin')], default=1, verbose_name='User Type'),
        ),
    ]
