# Generated by Django 5.0.3 on 2024-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_image',
        ),
        migrations.AddField(
            model_name='rooms',
            name='has_room_image',
            field=models.BooleanField(default=False),
        ),
    ]
