# Generated by Django 5.0.3 on 2024-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_rooms_room_image_rooms_has_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
