# Generated by Django 5.0.3 on 2024-07-04 16:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_rooms_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_code',
            field=models.CharField(default=api.models.generate_code, max_length=12, unique=True),
        ),
    ]
