# Generated by Django 5.0.3 on 2024-07-05 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rooms_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
