name: my-frontend-compose

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    network_mode: service:backend
    command: ["pnpm", "--filter", "frontend", "dev","--host", "0.0.0.0"]