name: my-frontend-compose

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    command: ["pnpm", "--filter", "frontend", "dev","--host"]
    volumes:
      - .:/app
      - /app/node_modules/