name: my-frontend-compose

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    command: ["pnpm", "--filter", "frontend", "dev","--host", "0.0.0.0"]
    ports:
      - "5173:5173"
      - "4173:4173"